#define HUD_VAMPIRE_BLOOD "vampire_blood"
#define HUD_VAMPIRE_RANK "vampire_rank"
#define HUD_VAMPIRE_HUMANITY "vampire_humanity"
#define HUD_VAMPIRE_SUNLIGHT "vampire_sunlight"
#define HUD_VASSAL_TRACKER "vassal_tracker"
